#application.yaml的优先级较低 项目刚一启动并不能读取
#bootstrap.application/yaml 的优先级较高
server:
  port: 80

#配置链路追踪地址
spring:
  zipkin:
    base-url: http://192.168.6.102:9411/
    sender:
      type: web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #允许所有地址来源跨域
            allowedMethods: "*"  #允许所有请求方式跨域
            allowedHeaders: "*"  #复杂跨域原因就是因为带来一些复杂的请求头导致
            allowCredentials: true #允许带一些安全标志跨域 比如:Cookie
      routes:
        - id: product_route #以admin/product开头的请求都lb(loadbalancer)转给service-product
          uri: lb://service-product
          predicates: #断言
            - Path=/admin/product/**

        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: cart_route
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**


        - id: web_all_route
          uri: lb://web-all
          predicates: #断言
            - Host=**.gmall.com


app:
  auth:
    no-auth-url: #任意人无需登入都能访问的路径
      - /css/**
      - /js/**
      - /img/**
      - /login.html
      - /api/user/passport/login
    login-auth-url: #登入后才能访问的资源
      - /order/**
    login-page: http://passport.gmall.com/login.html

    deny-url:
      - /api/inner/**