server:
  port: 7000

spring:
  profiles:
    include: sharding #包含的文件 不用区分激活的profile
  #  profiles:
#   active: sharding #主文件 application.yaml和激活的 application-{profile}.yaml 同时生效

  datasource:
    url: jdbc:mysql://192.168.6.102:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#自定义配置
app:
  minio:
    endpoint: http://192.168.6.102:9000
    ak: admin
    sk: admin123456
    bucketName: gmall

  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300 #单位秒